# Generated by Django 2.2.7 on 2019-11-17 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowers',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('all_util', models.FloatField(default=0.0)),
                ('annual_income', models.FloatField(default=0.0)),
                ('avg_cur_bal', models.FloatField()),
                ('dti', models.FloatField()),
                ('home_ownership', models.CharField(choices=[('MORTGAGE', 'MORTGAGE'), ('RENT', 'RENT'), ('OWN', 'OWN'), ('OTHER', 'OTHER')], default='OTHER', max_length=8)),
                ('address_state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='', max_length=2)),
                ('zip_code', models.CharField(max_length=3)),
                ('emp_title', models.CharField(max_length=256)),
                ('emp_length', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Borrowers',
            },
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('funded_amount', models.FloatField()),
                ('total_payments', models.FloatField()),
                ('grade', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4'), ('B5', 'B5'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4'), ('C5', 'C5'), ('D1', 'D1'), ('D2', 'D2'), ('D3', 'D3'), ('D4', 'D4'), ('D5', 'D5'), ('E1', 'E1'), ('E2', 'E2'), ('E3', 'E3'), ('E4', 'E4'), ('E5', 'E5'), ('F1', 'F1'), ('F2', 'F2'), ('F3', 'F3'), ('F4', 'F4'), ('F5', 'F5'), ('G1', 'G1'), ('G2', 'G2'), ('G3', 'G3'), ('G4', 'G4'), ('G5', 'G5')], max_length=2)),
                ('interest_rate', models.FloatField()),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('PAID', 'paid'), ('CURRENT', 'current'), ('CHARGED_OFF', 'charged off'), ('LATE1', 'late up to 60 weeks'), ('LATE2', 'late beyond 60 weeks'), ('GRACE', 'in grace period'), ('DEFAULT', 'default')], default='DEFAULT', max_length=12)),
                ('meets_policy', models.BooleanField(default=True)),
                ('term', models.CharField(choices=[('36', '36 months'), ('60', '60 months')], default='30', max_length=2)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.Borrowers')),
            ],
            options={
                'db_table': 'Loans',
            },
        ),
    ]
